name: Test Action
on:
  push:
    branches:
      main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Builds the ReSpec HTML
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ls
        run: "ls -al"
        shell: bash
      - name: Run respec_action
        uses: edsu/respec-action@v0.1.1
